angular.module("myApp",[]).controller(
    "loginController",function($scope){
        $scope.user={username:"",Password:""};
        $scope.isLogged=false;
        $scope.login=function(){
            $scope.isLogged=true;
        };
    }
);
